# Settings for the app
app:
  # HTML Title
  title: _(Williams Ave Community Garden)
  # Header name
  name: "_(Williams Ave Community Garden)"
  # Meta description that will show up in Google search results
  meta_description: "_(Welcome!)"
  # Meta author that will show up in Google search results
  meta_author: haxgeo.com

  # This should be set to the root of an api server from which you'd like to draw
  # permissions information for logged-in users. This value can be overridden
  # using the API_ROOT environment variable. Note the trailing slash.
  api_root: https://dev-api.heyduwamish.org/api/v2/

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

  # Header text in the summary view; custom for this flavor
  summary_page_header: _(Over the next few months, we will work with community members and local stakeholders to design a plan for the garden and begin construction soon after.)

languages:
  - code: en_US
    label: I Speak English

  - code: es
    label: Hablo Español

#   - code: vi
#     label: tôi nói tiếng việt

map:
# Settings for map and layer configs
  geolocation_enabled: true
  geolocation_onload: false
  cartodb_enabled: true
  #  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [46.500, -124, 48.5, -119] # south, west, north, east

  options:
    center:
      lat: 40.67428
      lng: -73.90083
    zoom: 17
    minZoom: 1
    maxZoom: 18

  layers:
    - id: osm
      url: //{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png

      attribution: <a href="/page/terms">Terms and conditions</a> &copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Mapbox</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: terrain
      type: basemap
      url: //stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png
      maxZoom: 16

    - id: satellite
      url: //api.tiles.mapbox.com/v4/smartercleanup.pe3o4gdn/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: williams-input
      url: https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/williams-input
      type: place
      slug: report

    - id: williams-project
      url: https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/williams-project
      type: place
      slug: project

    - id: williams-partners
      url: https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/williams-partners
      type: place
      slug: partners

    - id: transit-points
      type: wms
      url: https://geoserver.mapseed.org/geoserver/nyrp/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers:
        - transit_points

    - id: transit-lines
      type: wms
      url: https://geoserver.mapseed.org/geoserver/nyrp/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers:
        - transit_lines

    - id: biking
      type: wms
      url: https://geoserver.mapseed.org/geoserver/nyrp/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers:
        - ny_bike_lanes_2

    - id: zoning
      type: wms
      url: https://geoserver.mapseed.org/geoserver/nyrp/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers: 
        - ny_zoning_2

    - id: heatwaves
      type: wms
      url: https://geoserver.mapseed.org/geoserver/nyrp/wms?
      format: image/png
      version: 1.3.0
      transparent: true
      layers:
        - ny_heatwave

    - id: flood-zones
      url: //{s}.tiles.mapbox.com/v3/jkeefe.map-dg0rv3jh/{z}/{x}/{y}.png

# The values map the place type to map icons (defined below).
place_types:
  community_input:
    label: _(Comment)
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconUrl: /static/css/images/markers/comment-map-marker.svg
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: 'this.map.zoom < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-dbcf2c.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: 'this.map.zoom < 16'
        icon:
          iconUrl: /static/css/images/markers/comment-map-marker.svg
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: 'this.map.zoom >= 16'
        icon:
          iconUrl: /static/css/images/markers/comment-map-marker.svg
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  williams-partners:
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconSize: [50, 50]
          iconAnchor: [25, 25]
      - condition: 'this.map.zoom < 15'
        icon:
          iconUrl: /static/css/images/markers/marker-construction-dot.png
          iconSize: [10, 10]
          iconAnchor: [0, 0]
      - condition: 'this.map.zoom <= 18'
        icon:
          iconUrl: /static/css/images/markers/marker-construction.png
          iconSize: [30, 30]
          iconAnchor: [15, 15]

  williams-project:
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconSize: [50, 50]
          iconAnchor: [25, 25]
      - condition: 'this.map.zoom < 15'
        icon:
          iconSize: [10, 10]
          iconAnchor: [0, 0]
      - condition: 'this.map.zoom <= 18'
        icon:
          iconSize: [30, 30]
          iconAnchor: [15, 15]

sidebar:
  enabled: true
  panels:
    - id: gis-layers
      basemaps:
        - id: osm
          icon_url: /static/css/images/default-map.svg
          title: _(Default)
          visibleDefault: true
        - id: satellite
          icon_url: /static/css/images/satellite-map.svg
          title: _(Satellite)
          visibleDefault: false
        - id: terrain
          icon_url: /static/css/images/terrain-map.svg
          title: _(Terrain)
          visibleDefault: false
      groupings:
        - id: map-detail
          title: _(Map detail)
          layers:
            - id: transit_lines_and_points
              icon_url: /static/css/images/transit.svg
              title: _(Transit)
              constituentLayers:
                - transit-lines
                - transit-points
              visibleDefault: false
            - id: biking
              icon_url: /static/css/images/bike-lanes.svg
              title: _(Biking)
              visibleDefault: false
            - id: zoning
              icon_url: /static/css/images/zoning.svg
              title: _(Zoning)
              visibleDefault: false
            - id: williams-input
              icon_url: /static/css/images/comments.svg
              title: _(Comments)
              visibleDefault: true
            - id: williams-partners
              icon_url: /static/css/images/partners.svg
              title: _(Partners)
              visibleDefault: false
            - id: williams-project
              icon_url: /static/css/images/park-icon.png
              title: _(Project)
              visibleDefault: true
        - id: climate-risks
          title: _(Climate risks)
          layers:
            - id: heatwaves
              icon_url: /static/css/images/heatwaves.svg
              title: _(Heat Waves)
              visibleDefault: false
            - id: flood-zones
              icon_url: /static/css/images/flood-zones.svg
              title: _(Flood Zones)
              visibleDefault: false

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  adding_supported: true
  add_button_label: _(Add your comments)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Comments)
  show_map_button_label: _(Comments)
  action_text: _(added)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Put it on the map!)
  location_item_name: location

  #### begin dynamic form config ####
  place_detail:
    - category: williams-partners
      admin_only: true
      includeOnForm: true
      showMetadata: false
      suppressAttachments: true
      horizontal_rule: true
      name: location_type
      dataset: williams-partners
      icon_url: /static/css/images/partners-blue.svg
      value: featured_place
      label: _(Partner Site)
      fields:
        - name: published
          type: publish_control_toolbar
        - name: geometry
          type: map_drawing_toolbar
          content:
            - url: /static/css/images/partners-blue.svg
            - url: /static/css/images/markers/marker-star.png
        - name: address
          type: geocoding
          prompt: _(Location:)
          display_prompt: _(Address)
          placeholder: _(Enter address...)
          optional: true
        - name: title
          type: text
          prompt: _(Title of this featured site:)
          display_prompt: _( )
          placeholder: _(Enter title...)
          optional: false
        - name: description
          type: rich_textarea
          prompt: _( )
          display_prompt: _( )
          placeholder: _( )
        - name: url-title
          type: custom_url_toolbar
          prompt: _(Choose a custom URL for this place:)
          placeholder: "my-new-featured-place"
          optional: true
        - name: private-submitter_email
          type: common_form_element
        - name: submit
          type: common_form_element
    - category: williams-project
      admin_only: true
      includeOnForm: true
      showMetadata: false
      suppressAttachments: true
      horizontal_rule: true
      name: location_type
      dataset: williams-project
      icon_url: /static/css/images/park-icon.png
      value: featured_place
      label: _(Project Site)
      fields:
        - name: published
          type: publish_control_toolbar
        - name: geometry
          type: map_drawing_toolbar
          content:
            - url: /static/css/images/markers/marker-star.png
            - url: /static/css/images/markers/marker-bike.png
            - url: /static/css/images/markers/marker-construction.png
            - url: /static/css/images/markers/marker-foodforest.png
            - url: /static/css/images/markers/marker-greenwall.png
            - url: /static/css/images/markers/marker-heart.png
            - url: /static/css/images/markers/marker-hist_comp.png
            - url: /static/css/images/markers/marker-hist_no-prog-or-dead.png
            - url: /static/css/images/markers/marker-hist_prog.png
            - url: /static/css/images/markers/marker-land_comp.png
            - url: /static/css/images/markers/marker-land_no-prog-or-dead.png
            - url: /static/css/images/markers/marker-land_prog.png
            - url: /static/css/images/markers/marker-transp_comp.png
            - url: /static/css/images/markers/marker-transp_no-prog-or-dead.png
            - url: /static/css/images/markers/marker-transp_prog.png
        - name: title
          type: text
          prompt: _(Title of this featured site:)
          display_prompt: _( )
          placeholder: _(Enter title...)
          optional: false
        - name: description
          type: rich_textarea
          prompt: _( )
          display_prompt: _( )
          placeholder: _( )
        - name: url-title
          type: custom_url_toolbar
          prompt: _(Choose a custom URL for this place:)
          placeholder: "my-new-featured-place"
          optional: true
        - name: private-submitter_email
          type: common_form_element
        - name: submit
          type: common_form_element    
    - category: community_input
      includeOnForm: true
      name: location_type
      dataset: williams-input
      icon_url: /static/css/images/markers/marker-observation.png
      value: community_input
      label: _(Add a comment)
      fields:
        - name: private-age
          prompt: _(How old are you?)
          type: range
          max: 100
          min: 15
          default_value: 50
          # NOTE: in this flavor, the autocomplete: true flag causes autocompleted
          #       fields to be hidden on subsequent form renders.
          autocomplete: true
          horizontal_rule_below: true
        - name: regular_user
          type: big_toggle
          autocomplete: true
          prompt: _(Are you a regular user of this garden?)
          display_prompt: _(I am a regular user of this garden:)
          content:
            - label: _(Yes)
              value: "yes"
            - label: _(No)
              value: "no"
          optional: false
          horizontal_rule_below: true
        - name: children_at_home
          type: big_toggle
          autocomplete: true
          prompt: _(Do you have children at home?)
          display_prompt: _(I have children at home:)
          content:
            - label: _(Yes)
              value: "yes"
            - label: _(No)
              value: "no"
          optional: false
          horizontal_rule_below: true
        - name: language
          autocomplete: true
          type: dropdown
          prompt: _(What is your preferred language?)
          display_prompt: _(My preferred language:)
          content:
            - label: _(Bengali)
              value: bengali
            - label: _(Cantonese)
              value: cantonese
            - label: _(English)
              value: english
            - label: _(Mandarin)
              value: mandarin
            - label: _(Spanish)
              value: spanish
            - label: _(Other)
              value: other
          optional: true
        - name: private-submitter_email
          type: common_form_element
        - name: input_category
          prompt: _(What type of comment is this?)
          type: big_radio
          default_value: "recommendation"
          content:
            - label: _(Recommendation)
              label_plural: _(Recommendations)
              value: recommendation
            - label: _(Concern)
              label_plural: _(Concerns)
              value: concern
          optional: false
        - name: input_text
          type: textarea
          autocomplete: false
          prompt: _(What would encourage you to use this space more often?)
          display_prompt: _( )
          placeholder: _(Write your comment here)
          optional: false
        - name: input_subcategory
          prompt: _(Select any of the below categories that apply:)
          type: big_checkbox
          content:
            - label: _(Amenities)
              value: amenities
            - label: _(Horticulture)
              value: horticulture
            - label: _(Programs)
              value: programs
            - label: _(Safety)
              value: safety
            - label: _(Experience)
              value: experience
            - label: _(Other)
              value: other
          optional: true
        - name: submit
          type: common_form_element

  # define form elements that appear on every form here
  common_form_elements:
    submitter_name:
      type: text
      prompt: _(Your name)
      placeholder: _(Name)
      autocomplete: true
      optional: false
    private-submitter_email:
      type: text
      prompt: _(Enter your email address for updates)
      placeholder: _(name@mail.com)
      optional: true
      autocomplete: true
    my_image:
      type: file
      prompt: _(Image)
      label: _(Add an Image)
      optional: true
    submit:
      type: submit
      label: _(Submit comment)

  #### end dynamic form config ####

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Map)
    name: 17/40.67428/-73.90083

  - title: _(Project)
    slug: about
    name: overview
    start_page: true

cluster:
  animate: true
  animateAddingMarkers: false
  showCoverageOnHover: false
  spiderfyOnMaxZoom: true
  spiderfyDistanceMultiplier: 1.5
  spiderLegPolylineOptions:
    opacity: 0

custom_components:
  InputForm: VVInputForm
