# Settings for the app
app:
  # HTML Title
  title: Marra-Desimone park improvements
  # Header name
  name: Marra-Desimone Park
  # Meta description that will show up in Google search results
  meta_description: _(Come share your ideas on improving Marra-Desimone Park!)  
  # Meta author that will show up in Google search results
  meta_author: SmarterCleanup.org

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false



# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
#  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [46.500, -124, 48.5, -119] # south, west, north, east

  options:
    center:
      lat: 47.52111
      lng: -122.32667
    zoom: 18
    minZoom: 1
    maxZoom: 18
#    maxBounds: [[47.000, -123.26], [47.92, -120.67]] # south, west, north, east
#    maxBounds: [[46.500, -124], [48.5, -119]] # south, west, north, east
  layers:
#      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'
      # SmarterCleanup Mapbox base layer:
    - url: //{s}.tiles.mapbox.com/v4/smartercleanup.ndhd2lem/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      visible: true
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

  # Map Layers

     # Mapbox project freehand drawing imports
    - url: //a.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      type: json
      description: _(Places where positive restoration and community organizing are happening)
      popupContent: '{{title}}'
      legend: true
      visible: true
      title: _(Community action)
      rules:
      # show nothing when zoomed out
        - condition: '"{{map.zoom}}" < 11'

      # LineString
        - condition: '"{{geometry.type}}" == "LineString"'
          style:
            color: "{{properties.stroke}}"
            opacity: '{{properties.stroke-opacity}}'
            weight: "{{properties.stroke-width}}"
      # Polygons
        - condition: '"{{geometry.type}}" == "Polygon"'
          style:
            shapeType: polygon
            fillColor: "{{properties.fill}}"
            fill: 'true'
            color: "{{properties.stroke}}"
            opacity: 0.7
            fillOpacity: '{{properties.fill-opacity}}'
            weight: "{{properties.stroke-width}}"

      # Mapbox Points

        # Shrink the markers when zoomed out
#        - condition: '"{{map._zoom}}" < 11 && "{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "danger"'
#          icon:
#            iconUrl: /static/css/images/markers/marker-danger.png
#            iconSize: [10, 10]
#            iconAnchor: [5, 5]
#
#        - condition: '{{map._zoom}} < 11 && "{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "park2"'
#          icon:
#            iconUrl: /static/css/images/markers/marker-park.png
#            iconSize: [10, 10]
#            iconAnchor: [5, 5]
#
#        - condition: '{{map.view}} < 11 && "{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "industrial"'
#          icon:
#            iconUrl: /static/css/images/markers/marker-industrial.png
#            iconSize: [10, 10]
#            iconAnchor: [5, 5]
#
#        - condition: '{{map.view}} < 11 && "{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "bicycle"'
#          icon:
#            iconUrl: /static/css/images/markers/marker-bicycle.png
#            iconSize: [10, 10]
#            iconAnchor: [5, 5]

        # Regular marker display
#        - condition: '"{{properties.marker-symbol}}" === "danger" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "danger"'
          icon:
            iconUrl: /static/css/images/markers/marker-construction.png
            iconSize: [30, 30]
            iconAnchor: [15, 15]

        - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "park2"'
          icon:
            iconUrl: /static/css/images/markers/marker-treeheart.png
            iconSize: [40, 40]
            iconAnchor: [13, 13]

        - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "industrial"'
          icon:
            iconUrl: /static/css/images/markers/marker-industrial.png
            iconSize: [40, 40]
            iconAnchor: [20, 20]

        - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "bicycle"'
          icon:
            iconUrl: /static/css/images/markers/marker-bike.png
            iconSize: [30, 30]
            iconAnchor: [15, 15]

        # default point marker case
        - condition: '"{{geometry.type}}" == "Point"'
          icon:
            iconUrl: /static/css/images/markers/dot-fa307d.png
            iconSize: [16, 16]
            iconAnchor: [8, 8]

     # Mapbox project freehand drawing imports
    - url: //a.tiles.mapbox.com/v4/smartercleanup.mfigd1mf/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      type: json
      description: _(Places where pollution has been problematic)
      popupContent: '{{title}}'
      legend: true
      visible: true
      title: _(Areas of concern)
      rules:
      # show nothing when zoomed out
        - condition: '"{{map.zoom}}" < 11'

      # LineString
        - condition: '"{{geometry.type}}" == "LineString"'
          style:
            color: "{{properties.stroke}}"
            opacity: '{{properties.stroke-opacity}}'
            weight: "{{properties.stroke-width}}"
      # Polygons
        - condition: '"{{geometry.type}}" == "Polygon"'
          style:
            shapeType: polygon
            fillColor: "{{properties.fill}}"
            fill: 'true'
            color: "{{properties.stroke}}"
            opacity: 0.7
            fillOpacity: '{{properties.fill-opacity}}'
            weight: "{{properties.stroke-width}}"

      # WMS ROD
    - url: //d171ntg776wsmz.cloudfront.net/geoserver/wria9/gwc/service/wms
      layers: 'wria9:EPARODMergedFinal'
      version: '1.1.0'
      transparent: true
      format: 'image/png'
      legend: true
      opacity: 0.8
      description: <img src="/static/css/images/legend-EPA-ROD.png" alt="legend">
      title: Future cleanup plan
      visible: false

      # WMS landuse
    - url: //d171ntg776wsmz.cloudfront.net/geoserver/wria9/gwc/service/wms
      layers: 'wria9:Landuse2010'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      opacity: 0.5
      description: <img src="/static/css/images/legend-landuse2010.png" alt="legend">
      title: _(Land use data)
      visible: false

      # WMS Buildings connection:
    - url: //d171ntg776wsmz.cloudfront.net/geoserver/wria9/wms
      layers: 'wria9:2009BuildingsCOS'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      description: _(legend coming soon!)
      title: _(Buildings)
      visible: false

      # WMS NLCD
    - url: //d171ntg776wsmz.cloudfront.net/geoserver/wria9/wms
      layers: 'wria9:nlcd2011'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      opacity: 0.6
#      description: "_(key: <br>-The red area means more concrete coverage<br>-blue means water<br>-dark green means forested<br>-light green means grass or soil)"
      description: <img src="/static/css/images/legend-nlcd2011.png" alt="legend">
      title: _(Land coverage data)
      visible: false
      
      # WMS Original Flow
    - url: //d171ntg776wsmz.cloudfront.net/geoserver/wria9/wms
      layers: 'wria9:Historical_Flow'
      version: '1.1.0'
      transparent: 'true'
      format: 'image/png'
      legend: true
      opacity: 0.4
      description: _(The orginal Duwamish River path)
      title: _(Original river path)
      visible: false

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
 
  observation:
    label: _(Observation)
    rules:
      - condition: '"{{location_type}}" === "observation" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "observation" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "observation" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "observation" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

  question:
    label: _(Question)
    rules:
      - condition: '"{{location_type}}" === "question" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "question" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "question" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "question" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]
#      - condition: '"{{location_type}}" === "question" && {{layer.focused}}'
#        icon:
#          iconUrl: /static/css/images/markers/marker-question.png
#          shadowUrl: /static/css/images/marker-shadow.png
#          iconSize: [50, 60]
#          shadowSize: [50, 60]
#          shadowAnchor: [25, 60]
#          iconAnchor: [25, 60]
#
#      - condition: '"{{location_type}}" === "question"'
#        # Show questions that are points as icons...
#
#        icon:
#          iconUrl: /static/css/images/markers/marker-question.png
#          iconSize: [24, 29]
#          iconAnchor: [12, 29]
#
#        # ...and questions that are polygons as shapes.
#
#        style:
#          color: '#4bbd45'
#          weight: 1
#          opacity: 0.9
#          fillOpacity: 0.4

  idea:
    label: _(Idea)
    rules:
      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]
#      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 13 && {{layer.focused}} === false'
#        # Display landmarks as circles (vectors) when zoomed out
#
#        style:
#          color: '#0d85e9'
#          radius: 3
#          weight: 1
#          opacity: 0.9
#          fillOpacity: 1
#
#      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
#        # Display landmarks as icons when zoomed in
#
#        icon:
#          iconUrl: /static/css/images/markers/marker-idea.png
#          iconSize: [50, 60]
#          iconAnchor: [24, 59]
#
#      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
#        # Display landmarks as icons when zoomed in
#
#        icon:
#          iconUrl: /static/css/images/markers/marker-idea.png
#          shadowUrl: /static/css/images/marker-shadow.png
#          iconSize: [80, 96]
#          shadowSize: [41, 41]
#          iconAnchor: [39, 94]

  complaint:
    label: _(Complaint)
    rules:
      - condition: '"{{location_type}}" === "complaint" && {{map.zoom}} < 11 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '"{{location_type}}" === "complaint" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [24, 29]
          iconAnchor: [12, 29]

      - condition: '"{{location_type}}" === "complaint" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

      - condition: '"{{location_type}}" === "complaint" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

# Sidebar and activity stream should be enabled and disabled together!
# note: sidebar is aka 'MasterLegend'
# TODO: Couple the sidebar and activity stream because the activity stream is a component of the sidebar
sidebar:
  enabled: true
  legend_enabled: false
  slug: filter-type
  reports:
  - title: _(Observations)
    image: /static/css/images/markers/marker-observation.png
    url: /filter/observation
  - title: _(Ideas)
    image: /static/css/images/markers/marker-idea.png
    url: /filter/idea
  - title: _(Questions)
    image: /static/css/images/markers/marker-question.png
    url: /filter/question
  - title: _(Complaints)
    image: /static/css/images/markers/marker-complaint.png
    url: /filter/complaint
  - title: _(Hide Reports)
    url: /filter/none
    image: /static/css/images/hide-all.png
  - title: _(Show Reports)
    url: /
    image: /static/css/images/show-all.png

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  adding_supported: true
  add_button_label: _(Add a comment to the map)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(See list of comments)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Put it on the map!)

  location_item_name: location

  items:
    - prompt: _(Title of report)
      type: text
      name: name
      optional: true
      attrs:
        - key: placeholder
          value: _(Enter title)
        - key: size
          value: 30
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Type of report)
      type: select
      options:
        - label: _(Observation)
          value: observation
        - label: _(Question)
          value: question
        - label: _(Idea)
          value: idea
        - label: _(Complaint)
          value: complaint
      name: location_type
      attrs:
        - key: required
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true